manifest:
  version: 0.13
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Zephyr 主專案
    - name: zephyr
      path: deps/zephyr
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_stm32

    # 必要的 ARM CMSIS
    - name: cmsis
      path: deps/modules/hal/cmsis
      revision: main

    # STM32 HAL
    - name: hal_stm32
      path: deps/modules/hal/stm32
      revision: main

    # 如果需要 bootloader
    # - name: mcuboot
    #   path: deps/bootloader/mcuboot
    #   revision: main

  self:
    path: .
